[package]
name = "wok_db_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
derime = { path = "../derime" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
