[package]
name = "wok_core"
version = "0.1.0"
edition = "2024"

[dependencies]
async_fn_traits = "0.1.1"
futures = { workspace = true }
wok_derive = { path = "../wok_derive" }
async-channel = { workspace = true }
thiserror = { workspace = true }
