[package]
name = "serdeenv_toml"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
