[package]
name = "valigate"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
valigate_derive = { path = "../valigate_derive" }
chrono = { workspace = true, optional = true }
serde = { workspace = true }

[features]
default = ["chrono"]
chrono = ["dep:chrono"]
